### ISSUE TITLE
New Feature Roadmap - 1.x Beta

### ISSUE THREAD

**Issue by codeHusky** [codeHusky/HuskyCrates-Sponge#20]
#### Items are checked off and then removed after their appropriate version is released

- Pending lang modifications
   - [ ] Receive vkey
   - [ ] Receive key
   - [ ] Receive key (ender)
   - **NYI Entries**
   - [ ] Purchase Key (No Key)
   - [ ] Purchase Key Success
   - [ ] Purchase Key Failure
- [x] Randomize crate reward order to give additional randomness.
- [x] Show all possible rewards on right click
   - [ ] Allow server owners to bind right click to commands rather than the toggleable right click reward list
- [ ] Advanced Key System `advancedKeys=true`
   - [ ] Treat keys as regular items, parse with normal item parser.
   - [ ] Keys are defined (optionally) separately from the crate.
      - possibly enabled via `advancedKeys=true` in options
      - configured in `keyOptions{}`
   - [ ] Crates can take multiple of the same key to open once
   - [ ] Crates can take multiple types of keys
- [ ] Economy integration
- [ ] customizable UI (the dark gray glass panes, replace with whatever.)
- [ ] Placeable supply-crate type crates which destroy after use.
   - Probably "keyless".
   - Use key on command to get placeable supply crate

*Post your suggestions below*

**Comment by codeHusky** [comment]
out of date, will be making new issue
