### ISSUE TITLE
Ongoing competing standards to-do list 

### ISSUE THREAD

**Issue by codeHusky** [codeHusky/HuskyCrates-Sponge#32]
- [ ] Virtual Keys (keys stored in config)
- [ ] customizable crate reward messages 
- [ ] Better key customization
