### ISSUE TITLE
v2.x general todo list

### ISSUE THREAD

**Issue by codeHusky** [codeHusky/HuskyCrates-Sponge#78]
**2.0.0**
- [x] Add freecrate features in
- [x] Reward Groups
- [x] Custom effect events (w/ effect reward)
- [ ] Entity Crate Support
- [ ] Implement all old views into new system
- Write proper command system
  - [x] Key Command
  - [x] Crate Block Command
  - [x] Main Command
  - [x] Reload Command
- [x] Add dupe warning code w/ hiss, etc
- [x] Fix huskyui, add paging to it, maybe.
- [x] Keys can launch crates
- [ ] Single-use "Free crate" items, usable by player by placing / secondary interaction

**2.1.0**
- [ ] Custom sounds for views
- [ ] #77 (BLP system)
- [ ] Cosmic Chest View
  - ![img](https://proxy.spigotmc.org/5fc329d5bb4f967ccb11e75b2b4ff93c0bc8a93d?url=https%3A%2F%2Flh4.googleusercontent.com%2FKCn9i1u8p5zeN4-jbGt46gcmjlFfzdH83wrGK9Uk_YEUQTNePdvkAl7KUdfR96h7i16KqGE_nJKIpWPNhUSOYfDCnEikbZlLc2_wrbi_3f78m4ztmkoNgYbIoCWuETH7sw)
- [ ] Randomized/Customizable automatic/manual single-use crate placement
  - Place safely in world within world border
  - Settings for time expiry, amount of openings...
  - Via commands `/hc placecrate <crate> <x,y,z or random> [expiryInSeconds] [useCount]`
- [x] eat food
